apiVersion: v1
baseDomain: ${baseDomain}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ${az1}
      - ${az2}
      - ${az3}
      rootVolume:
        iops: 4000
        size: 300
        type: io1
      type: ${master-instance-type}
  replicas: ${master_replica_count}
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - ${az1}
      - ${az2}
      - ${az3}
      rootVolume:
        iops: 2000
        size: 300
        type: io1
      type: ${worker-instance-type}
  replicas: ${worker_replica_count}
metadata:
  name: ${clustername}
networking:
  clusterNetwork:
  - cidr: ${clusternetworkcidr}
    hostPrefix: 23
  machineNetwork:
  - cidr: ${vpccidr}
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ${region}
    subnets:
    - ${public-subnet-1}
    - ${public-subnet-2}
    - ${public-subnet-3}
    - ${private-subnet-1}
    - ${private-subnet-2}
    - ${private-subnet-3}
pullSecret: '${pullSecret}'
fips: ${fips-enable}
sshKey: ${sshKey}
publish: ${private-public}
